export const Format = {
  HARDCOVER: "HARDCOVER",
  PAPERBACK: "PAPERBACK",
  MASS_MARKET_PAPERBACK: "MASS_MARKET_PAPERBACK",
  KINDLE_EDITION: "KINDLE_EDITION",
  LEATHER_BOUND: "LEATHER_BOUND",
  AUDIO_CASSETTE: "AUDIO_CASSETTE",
  AUDIO_CD: "AUDIO_CD",
  AUDIO: "AUDIO",
  EBOOK: "EBOOK",
  KINDLE: "KINDLE",
  PDF: "PDF",
  BROCHURA: "BROCHURA",
  PAPER: "PAPER",
  BONDED_LEATHER: "BONDED_LEATHER",
  SOFTCOVER: "SOFTCOVER",
  ALBUM: "ALBUM",
  COMIC: "COMIC",
  WEB: "WEB",
  DIARY: "DIARY",
  TURTLEBACK: "TURTLEBACK",
  WATTPAD: "WATTPAD",
  OTHER: "OTHER",
} as const;

export type Format = typeof Format[keyof typeof Format];

export const FormatLabel: Record<Format, string> = {
  HARDCOVER: "Hardcover",
  PAPERBACK: "Paperback",
  MASS_MARKET_PAPERBACK: "Mass Market Paperback",
  KINDLE_EDITION: "Kindle Edition",
  LEATHER_BOUND: "Leather Bound",
  AUDIO_CASSETTE: "Audio Cassette",
  AUDIO_CD: "Audio CD",
  AUDIO: "Audio",
  EBOOK: "Ebook",
  KINDLE: "Kindle",
  PDF: "PDF",
  BROCHURA: "Brochura",
  PAPER: "Paper",
  BONDED_LEATHER: "Bonded Leather",
  SOFTCOVER: "Softcover",
  ALBUM: "Album",
  COMIC: "Comic",
  WEB: "Web",
  DIARY: "Diary",
  TURTLEBACK: "Turtleback",
  WATTPAD: "Wattpad",
  OTHER: "Other",
};

export const AuthorRole = {
  AUTHOR: "AUTHOR",
  ILLUSTRATOR: "ILLUSTRATOR",
  COLORIST: "COLORIST",
  TRANSLATOR: "TRANSLATOR",
  INTRODUCTION_AUTHOR: "INTRODUCTION_AUTHOR",
  FOREWORD_AUTHOR: "FOREWORD_AUTHOR",
  AFTERWORD_AUTHOR: "AFTERWORD_AUTHOR",
  PREFACE_AUTHOR: "PREFACE_AUTHOR",
  ANNOTATIONS: "ANNOTATIONS",
  LETTERER: "LETTERER",
  CONTRIBUTOR: "CONTRIBUTOR",
  EDITOR: "EDITOR",
  NARRATOR: "NARRATOR",
  ARTIST: "ARTIST",
  NOTES: "NOTES",
  COMMENTARY: "COMMENTARY",
  OTHER: "OTHER",
} as const;

export type AuthorRole = typeof AuthorRole[keyof typeof AuthorRole];

export const AuthorRoleLabel: Record<AuthorRole, string> = {
  AUTHOR: "Author",
  ILLUSTRATOR: "Illustrator",
  COLORIST: "Colorist",
  TRANSLATOR: "Translator",
  INTRODUCTION_AUTHOR: "Introduction Author",
  FOREWORD_AUTHOR: "Foreword Author",
  AFTERWORD_AUTHOR: "Afterword Author",
  PREFACE_AUTHOR: "Preface Author",
  ANNOTATIONS: "Annotations",
  LETTERER: "Letterer",
  CONTRIBUTOR: "Contributor",
  EDITOR: "Editor",
  NARRATOR: "Narrator",
  ARTIST: "Artist",
  NOTES: "Notes",
  COMMENTARY: "Commentary",
  OTHER: "Other",
};
